#!/usr/bin/env bash
# pre-compact.sh — NEEWE PreCompact hook (Sprint 5 wave 2)
#
# Fires before Claude Code auto-compacts the conversation. Triggers a
# /context-save equivalent: snapshots state.json + git state + recent
# decisions to .neewe/handoffs/precompact-<session_id>-<timestamp>.md so
# the post-compact session can re-hydrate cleanly.
#
# Pattern lifted from TOK PreCompact → SessionStart rehydrate flow.
#
# Defensive: silent no-op if .neewe/state.json missing.

set -uo pipefail

STATE_FILE=".neewe/state.json"
if [ ! -f "$STATE_FILE" ]; then exit 0; fi

# Read session id from hook stdin if available.
HOOK_INPUT=$(cat 2>/dev/null || echo "{}")
SESSION_ID="unknown"
if command -v jq >/dev/null 2>&1; then
  SESSION_ID=$(echo "$HOOK_INPUT" | jq -r '.session_id // .sessionId // "unknown"' 2>/dev/null | tr -dc 'a-zA-Z0-9_-' | head -c 64)
fi
if [ -z "$SESSION_ID" ]; then SESSION_ID="unknown"; fi

mkdir -p ".neewe/handoffs"
TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
OUT_FILE=".neewe/handoffs/precompact-${SESSION_ID}-${TIMESTAMP}.md"

{
  echo "# NEEWE PreCompact Snapshot"
  echo ""
  echo "**Session:** $SESSION_ID"
  echo "**Timestamp:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "**Trigger:** PreCompact hook (Claude Code auto-compaction about to fire)"
  echo ""
  echo "## State (snapshot of .neewe/state.json)"
  echo '```json'
  cat "$STATE_FILE"
  echo '```'
  echo ""
  echo "## Git State"
  echo "**Branch:** $(git branch --show-current 2>/dev/null || echo '(not a git repo)')"
  echo "**HEAD:** $(git rev-parse --short HEAD 2>/dev/null || echo '(no HEAD)')"
  echo ""
  echo "### Last 5 Commits"
  echo '```'
  git log --oneline -5 2>/dev/null || echo "(no git log available)"
  echo '```'
  echo ""
  echo "### Working Tree (porcelain)"
  echo '```'
  git status --porcelain 2>/dev/null | head -20 || echo "(clean or no git)"
  echo '```'
  echo ""
  echo "## Recent Decisions (last 5 from vault)"
  if [ -d ".neewe/vault/decisions" ]; then
    ls -t .neewe/vault/decisions/*.md 2>/dev/null | head -5 | while IFS= read -r f; do
      echo "- $f"
    done
  else
    echo "(no .neewe/vault/decisions/ yet)"
  fi
  echo ""
  echo "## Latest Gate Verdicts"
  if [ -d ".neewe/gates" ]; then
    find .neewe/gates -name "aggregate.json" -type f 2>/dev/null | head -3 | while IFS= read -r f; do
      echo "- $f"
    done
  else
    echo "(no .neewe/gates/ yet)"
  fi
  echo ""
  echo "## Continuation Prompt (paste after /clear if not auto-rehydrated)"
  echo '```'
  echo "/context-restore $OUT_FILE"
  echo '```'
  echo ""
  echo "---"
  echo "*Auto-generated by pre-compact.sh hook. Session-start hook (with source=compact) will surface this for re-hydration.*"
} > "$OUT_FILE"

# Toast (verbosity-aware) for the agent + user
if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ] && [ -f "${CLAUDE_PLUGIN_ROOT}/hooks/lib/toast.sh" ]; then
  . "${CLAUDE_PLUGIN_ROOT}/hooks/lib/toast.sh"
  toast "Context snapshot saved before compact → ${OUT_FILE}"
else
  echo "[neewe-pre-compact] snapshot saved → $OUT_FILE" >&2
fi

# Update vault/log.md if it exists.
if [ -f ".neewe/vault/log.md" ]; then
  printf '\n## [%s] precompact-save | session=%s → %s\n' \
    "$(date -u +"%Y-%m-%d")" "$SESSION_ID" "$OUT_FILE" >> ".neewe/vault/log.md"
fi

exit 0
